version: '3.8'
services:
  web:
    build: .
    container_name: API
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./batch_files:/code/batch_files
      - ./processed_batches:/code/processed_batches
