FROM python:3.8
WORKDIR /code

RUN mkdir /code/batch_files
RUN mkdir /code/processed_batches

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# execute using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]